[General]
logType = "async"
separateUpdateEnabled = false
showSplash = true
Fullscreen = true
checkCompatibilityOnStartup = true
updateChannel = "Nightly"
logFilter = ""
enableDiscordRPC = false
compatibilityEnabled = true
autoUpdate = false
userName = "shadPS4"
isTrophyPopupDisabled = false
playBGM = false
isPS4Pro = false
BGMvolume = 50

[Input]
cursorState = 1
cursorHideTimeout = 5
backButtonBehavior = "left"
specialPadClass = 1
useSpecialPad = false

[GPU]
screenWidth = 1280
screenHeight = 720
nullGpu = false
copyGPUBuffers = false
vblankDivider = 1
dumpShaders = false
patchShaders = true

[Vulkan]
gpuId = -1
validation = false
rdocMarkersEnable = false
validation_sync = false
validation_gpu = false
rdocEnable = false
crashDiagnostic = false

[Debug]
DebugDump = false
CollectShader = false

[GUI]
gameTableMode = 0
mw_width = 1280
geometry_x = 0
iconSize = 36
emulatorLanguage = "en"
iconSizeGrid = 69
elfDirs = []
mw_height = 718
addonInstallDir = "/run/media/mmcblk0p1/Emulation/storage/shadps4/dlc"
pkgDirs = []
sliderPosGrid = 0
geometry_h = 718
geometry_y = 28
recentFiles = []
sliderPos = 0
installDirs = ["/run/media/mmcblk0p1/Emulation/storage/shadps4/games"]
theme = 0
geometry_w = 1280

[Settings]
consoleLanguage = 1
